/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.payroll;
import java.awt.Cursor;
import java.awt.Menu;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author Mata
 */
public class PayrollTimeLogger extends javax.swing.JFrame {

    int attempt = 3;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Connection conn1 = null;
    ResultSet rs1 = null;
    PreparedStatement pst1 = null;
    Connection conn2 = null;
    ResultSet rs2 = null;
    PreparedStatement pst2 = null;
            
    /**
     * Creates new form PayrollTimeLogger
     */
    public PayrollTimeLogger() {
        initComponents();
        
        conn=db.java_db();
        Calendar();
      //  TimeOut.setVisible(false);
    }
    public void Calendar(){
        Thread clock = new Thread(){
            
            public void run(){
                for (;;){
                    Calendar cal = Calendar.getInstance();
                    cal.getTime();
                    SimpleDateFormat sdf = new SimpleDateFormat("MMMM/dd/yyyy hh:mm:ss a");
    //                DateTime.setText(sdf.format(cal.getTime()));
                    
                    try{
                        sleep (1000);
                    }
                    catch(InterruptedException ex){
                        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE,null,ex);
                    } }}};
        clock.start();
                }
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        DateTime1 = new javax.swing.JLabel();
        EmployeeID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        TimeOut = new javax.swing.JButton();
        TimeIn = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Login");
        setBackground(new java.awt.Color(0, 0, 153));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DateTime1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DateTime1.setForeground(new java.awt.Color(255, 255, 255));
        DateTime1.setText("Employee ID:");
        jPanel1.add(DateTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 110, 130, 26));
        jPanel1.add(EmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 220, 30));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 130, -1));
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 220, 31));

        TimeOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TimeOut.setForeground(new java.awt.Color(0, 0, 153));
        TimeOut.setText("Timeout");
        TimeOut.setName(""); // NOI18N
        TimeOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeOutActionPerformed(evt);
            }
        });
        jPanel1.add(TimeOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));
        TimeOut.getAccessibleContext().setAccessibleName("TimeOut");

        TimeIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TimeIn.setForeground(new java.awt.Color(0, 51, 153));
        TimeIn.setText("TimeIn");
        TimeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeInActionPerformed(evt);
            }
        });
        jPanel1.add(TimeIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void TimeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeInActionPerformed
        // TODO add your handling code here:
        
            String sql = "SELECT U.id,U.username,U.Password,s.first_name,s.surname FROM staff_information s, Users U where s.ID=u.ID and s.ID=?";
            
        //comment
        String EnteredPassword=Password.getText();
        String DBusername;
        String DBpassword="";
        String fname="";
        String sname="";
        
         if ( EmployeeID.getText().isEmpty() ){
         JOptionPane.showMessageDialog(null, "You did not enter any ID");
          return; 
        }
        
        Date date = new Date();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss");
        try{
            
            int count =0;
            
            pst = conn.prepareStatement(sql);
            pst.setString(1, EmployeeID.getText());
         
      
            
            rs = pst.executeQuery();
                
                while(rs.next()){
                    int id = rs.getInt(1);
                    
                    DBusername=rs.getString(2);
                    DBpassword=rs.getString(3);
                    fname=rs.getString("first_name");
                    sname=rs.getString("surname");
                   
                }
            
          
          
            
                if(EnteredPassword.equals(DBpassword)){
                    
                        String strDate = dateFormat.format(date);
                        
                        String val1= EmployeeID.getText();
                        String val2="0";
                        String val3=strDate;
                                
                         sql ="insert into TimeLogsRaw  (EmployeeID,Event,EventDate) values ('"+val1+"', '"+val2+"', '"+val3+"')" ;
                        pst=conn.prepareStatement(sql);
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "Hello " + fname+" " + sname+". \n"+" You succssefully registered TimeIn at " +  strDate);
                                
                      //  MainMenu j = new MainMenu();
                      //  j.setVisible(true);
                      //  this.dispose();
                   
                }   
                    else{
                        JOptionPane.showMessageDialog(null, "ID and Password you entered are wrong!");
                    }
                
            
            
        }
        
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }
        finally{
            
            try{
                rs.close();
                pst.close();
            }
            catch(Exception e){
                
            }
        }
        
         EmployeeID.setText("");
       Password.setText("");
        
                                            

        
        
    }//GEN-LAST:event_TimeInActionPerformed

    private void TimeOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeOutActionPerformed
        // TODO add your handling code here:
        
            String sql = "SELECT U.id,U.username,U.Password,s.first_name,s.surname FROM staff_information s, Users U where s.ID=u.ID and s.ID=?";
            
        //comment
        String EnteredPassword=Password.getText();
        String DBusername;
        String DBpassword="";
        String fname="";
        String sname="";
        
         if ( EmployeeID.getText().isEmpty() ){
         JOptionPane.showMessageDialog(null, "You did not enter any ID");
          return; 
        }
        
        Date date = new Date();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss");
        try{
            
            int count =0;
            
            pst = conn.prepareStatement(sql);
            pst.setString(1, EmployeeID.getText());
         
      
            
            rs = pst.executeQuery();
                
                while(rs.next()){
                    int id = rs.getInt(1);
                    
                    DBusername=rs.getString(2);
                    DBpassword=rs.getString(3);
                    fname=rs.getString("first_name");
                    sname=rs.getString("surname");
                   
                }
            
          
          
            
                if(EnteredPassword.equals(DBpassword)){
                    
                        String strDate = dateFormat.format(date);
                        
                        String val1= EmployeeID.getText();
                        String val2="1";
                        String val3=strDate;
                                
                         sql ="insert into TimeLogsRaw  (EmployeeID,Event,EventDate) values ('"+val1+"', '"+val2+"', '"+val3+"')" ;
                        pst=conn.prepareStatement(sql);
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "Hello " + fname+" " + sname+". \n"+" You succssefully registered TimeOut at " +  strDate);
                                
                      //  MainMenu j = new MainMenu();
                      //  j.setVisible(true);
                      //  this.dispose();
                   
                }   
                    else{
                        JOptionPane.showMessageDialog(null, "ID and Password you entered are wrong!");
                    }
                
            
            
        }
        
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }
        finally{
            
            try{
                rs.close();
                pst.close();
            }
            catch(Exception e){
                
            }
        }
        
       EmployeeID.setText("");
       Password.setText("");
       
                                            

        
        
    }//GEN-LAST:event_TimeOutActionPerformed
       
                     
                        
              
        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayrollTimeLogger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayrollTimeLogger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayrollTimeLogger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayrollTimeLogger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayrollTimeLogger().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateTime1;
    private javax.swing.JTextField EmployeeID;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton TimeIn;
    private javax.swing.JButton TimeOut;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
